projects:
  GlacierTest AppSync:
    schemaPath: ../../../../../../../src/main/graphql/schema.json
    includes:
      - /src/main/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: ''
        generatedFileName: ''
        docsFilePath: /src/main/graphql/com/amazonaws/amplify/generated/graphql
        region: us-east-1
        apiId: sv5epdhjzrgnvj7cgzwyemibyy
        maxDepth: 2
