projects:
  GlacierAppSyncAPI:
    schemaPath: src/main/graphql/schema.json
    includes:
      - src/main/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: ''
        generatedFileName: ''
        docsFilePath: src/main/graphql/com/amazonaws/amplify/generated/graphql
        region: us-east-1
        apiId: yj3jdpw2fjeirlrepieu3kkhna
        maxDepth: 2
extensions:
  amplify:
    version: 3
