projects:
  GlacierAppSync:
    schemaPath: android-messenger/src/main/graphql/schema.json
    includes:
      - android-messenger/src/main/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: ''
        generatedFileName: ''
        docsFilePath: >-
          android-messenger/src/main/graphql/com/amazonaws/amplify/generated/graphql
        region: us-east-1
        apiId: ttnai7yxq5ba5fizvggj6rjebq
        maxDepth: 2
